export type AppErrorCode =
  | "VALIDATION_ERROR"
  | "NOT_FOUND"
  | "CONFLICT"
  | "INTERNAL_ERROR"
  | "SERVER_ERROR"
  | "SERVICE_UNAVAILABLE"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "TOKEN_REVOKED"
  | "TOKEN_EXPIRED"
  | "TOKEN_INVALID"
  | "ALREADY_AUTHENTICATED"
  | "BAD_REQUEST";
