name: FIT Webapp Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    enabled: true
    type: default
  - key: userId
    value: '1'
    enabled: true
    type: default
  - key: eventId
    value: '1'
    enabled: true
    type: default
  - key: registrationId
    value: '1'
    enabled: true
    type: default
